### PR TITLE
Created a container versioning system

### PR DESCRIPTION
**Pull request by chris-cheshire**
We now have a `VERSION` file in each of the module root directories that can be updated. I have then changed all the github action script to tag images with `latest` and `base-VERSION` - for specialist containers `base` can be replaced by something else like with guppy where its `cpu-1.0.0` and `gpu-1.0.0`. All the container versioning is automated except for the actual version number. 

We can talk about auto-incrementing and creating a version based on the github commit etc later on

### CODE REVIEW

**Comment by sidorov-si** [comment]
Hey Chris!

Overall, it looks good, but the following modules lack the VERSION files: `bedtools`, `cutadapt`, `fastqc`, `homer`, `htseq`, `luslab_genome_tools`, `luslab_linux_tools`, `luslab_util`, `macs2`, `metadata`, `multiqc`, `velocyto`. Probably, we want to version all our modules?

**Comment by chris-cheshire** [comment]
Perhaps, we wouldnt be doing anything with the version number right now though - unless we had a nice little script to gather and display them at runtime in a pipeline or something - might actually be a nice idea for reproducibility

**Comment by sidorov-si** [comment]
@chris-cheshire Yes, that certainly is a good idea! But do you want to add VERSION files to the rest of the modules? :)

**Comment by sidorov-si** [comment]
Oh, I see the commit now, sorry!

**Review by sidorov-si — APPROVED** [review]
All good!

**Pull request merged**
