### PR TITLE
Feat mod resources

### PR DESCRIPTION
**Pull request by sidorov-si**
I've put resource labels to all processes in all modules and tested the `fastqc` and `guppy` modules on CAMP. For the `guppy` module, the switches that calculate the label based on whether the developer wants to use CPUs or GPUs work, but I wasn't able to run the module on GPUs due to the following error:

`sbatch: error: slurm_job_submit: Requesting gpu node without a GRES request...`

Probably, these GRES are just not configured in slurm on CAMP: https://slurm.schedmd.com/gres.html

@amchakra Nobby, could you please add a tick box about setting resource labels in processes into the PR header?

# luslab-nf-modules

Thank you for contributing and submitting a pull request!

Please check you have done the following:

## Uniform coding style

- [x] Used snake_case rather than camelCase
- [x] Followed the output channel naming convention (e.g. `bam` for BAM files, `bed` for BED files)

## Continuous integration

- [x] Added any new modules to `.github/workflows/modules-testing.yml`
- [x] Added any new containers to `.github/workflows/docker-build-push.yml` and `.github/workflows/docker-linting.yml`
- [x] Added any new workflows to `.github/workflows/workflow-testing.yml`
- [x] Added any new test data to `test_data`
- [x] Bumped the version when changing an existing module
  - Major.Minor.Patch
    - Major for breaking changes
    - Minor for feature updates and most things
    - Patch for bug fixes and small things like comment and variable name updates

## Review

- [x] Selected some reviewers
- [x] Assigned yourself to the PR
- [x] Tagged the PR appropriately

### CODE REVIEW

**Comment by sidorov-si** [comment]
An important thing is that as now memory and CPU allocations are uncoupled from a queue, a developer can, in principle set a label with too much memory for a regular queue. I don't think we can control this programmatically anymore, but I retained the variables with the max resources per queue in the Crick config and in a comment there asked developers to pay attention to these maximum allowances when setting resource labels.

**Comment by amchakra** [comment]
I've added a tick box to the PR header

**Review by mjmansfi — COMMENTED** [review]
- `macs` - is minimum cores/memory enough? Without really knowing, I would guess more memory would be safe (and it probably scales well with cores)
- `mafft` - could safely be `high_cores` or less
- `samtools` - `samtools view` and `samtools sort` scale well with increasing resources - you could safely use  `low_cores` for likely better performance without requesting too much from the queue

**Comment by sidorov-si** [comment]
@amchakra Thank you Nobby!
@mjmansfi Thank you Mike for your comments! I adjusted the cores for `mafft` and memory for `macs2` (and in the same way for another caller, `seacr`). I retained just one core for `macs2` as I'm not sure about `macs2` parallelisation, and Chris advised me for one core. I also didn't change allowances for `samtools`, because `sort` and `view` already had `low_cores`. Did you mean allocating more cores to them somewhere outside the `samtools` module where `samtools` are used in addition to the main command?

**Review by chris-cheshire — APPROVED** [review]

**Pull request merged**
