### PR TITLE
Feat mod containers

### PR DESCRIPTION
**Pull request by sidorov-si**
A bunch of modules are moved to single-tool and mulled biocontainers. So now we have only 5 module containers to maintain.

### CODE REVIEW

**Comment by sidorov-si** [comment]
Hey @chris-cheshire ! I can see that github tried to do linting checks on mulled biocontainers. I excluded the modules with mulled biocontainers from docker linting checks in my branch, but I guess github looks into linting checks in master? What shall I do with this? And I also included `peka` into testing, and tests passed; I just thought, - was it excluded for some reason? (It seemed that tests for `peka` took quite a long time though).

**Comment by mjmansfi** [comment]
Somehow I cannot get the biocontainer to behave

**Comment by chris-cheshire** [comment]
Do the linting checks fail for mulled containers? Yes, peka has been removed because it takes too long, its not a core module anyway and is only used in one pipeline.

**Review by alexthiery — APPROVED** [review]

**Comment by sidorov-si** [comment]
Hi @chris-cheshire ! GitHub tries to check Docker linting of the seven mulled biocontainers and waits "for status to be reported" indefinitely. I removed the corresponding modules from Docker testing in my branch, but it seems that GitHub uses Docker testing config from master brach, where these modules are still present. 

Thank you for the info about `peka`! I excluded it again from testing.

**Comment by chris-cheshire** [comment]
Hey slava, this is just the github actions expecting the test to run but it not being there - I have removed them from the list of expected tests now - update from master and I can approve the review then

**Comment by sidorov-si** [comment]
Thank you @chris-cheshire ! Done.

**Pull request merged**
