### PR TITLE
build docker image before adding r module

### PR DESCRIPTION
**Pull request by alexthiery**
# luslab-nf-modules

Thank you for contributing and submitting a pull request!

Please check you have done the following:

## Uniform coding style

- [x] Used snake_case rather than camelCase
- [x] Followed the output channel naming convention (e.g. `bam` for BAM files, `bed` for BED files)
- [x] Set the resource label for a new process

## Continuous integration

- [ ] Added any new modules to `.github/workflows/modules-testing.yml`
- [x] Added any new containers to `.github/workflows/docker-build-push.yml` and `.github/workflows/docker-linting.yml`
- [x] Added any new workflows to `.github/workflows/workflow-testing.yml`
- [x] Added any new test data to `test_data`
- [x] Bumped the version when changing an existing module
  - Major.Minor.Patch
    - Major for breaking changes
    - Minor for feature updates and most things
    - Patch for bug fixes and small things like comment and variable name updates

## Review

- [x] Selected some reviewers
- [x] Assigned yourself to the PR
- [x] Tagged the PR appropriately

### CODE REVIEW

**Comment by mjmansfi** [comment]
Hmm, what am I missing here? I don't see a `main.nf` or `test/main.nf`, and therefore the use for `test_data/r/test.csv`. Those might make the intention more clear, although it is useful to have a generic R container (personally, I do not use `ggplot2`, so base R is fine by me). 

As an aside, the `rocker` image is super fast to build/push, so `minionqc` and future R-based Docker images could use `rocker` as a base image instead of what they're doing now.

**Comment by alexthiery** [comment]
So I have the module waiting to go, but I the image on dockerhub in order to run the module tests.

I couldnt remember how we manage this, so I was just pushing the image first before adding the rest of the module

**Comment by marc-jones** [comment]
I don't think you need the image on DockerHub for the tests to run. The GitHub action in `modules-testing.yml` will create the image and tag it [such that it's used for the test](https://github.com/luslab/luslab-nf-modules/blob/fcaf350b3386a9e4727833644125f813b3549e4e/.github/workflows/modules-testing.yml#L43).

**Comment by marc-jones** [comment]
So you should be able to include the module in this PR and your new tests will run okay.

**Comment by alexthiery** [comment]
Ah ok great thanks both! Will add the rest of the mod

**Comment by alexthiery** [comment]
Ah ok great thanks both - should've checked the testing workflow! Will add the rest of the mod.

**Comment by marc-jones** [comment]
Haha, only reason I delved into the testing workflow is I had a similar "how on earth is it doing that?!" moment!

**Review by chris-cheshire — APPROVED** [review]

**Review by chris-cheshire — APPROVED** [review]

**Review by chris-cheshire — APPROVED** [review]

**Pull request merged**
